spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: byasebastien1991@gmail.com
    password: chwz wkgp jwtx ihvo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
